### ISSUE TITLE
Getting this error, Can anyone help?

### ISSUE THREAD

**Issue by yaasin12** [SharlSherif/Generate-HoustonLibrary-Codes#6]
Sorry i'm a bit bad with node.js, can anyone help me with this error?

c:\Users\Yaas\Desktop\Generate-HoustonLibrary-Codes-master>node app.js
Script is running on port 5000

Opening the headless browser..

Started the process..

Gathering fake information..

Going to Houstonlibrary website..

(node:2444) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot set property 'value' of null
    at __puppeteer_evaluation_script__:12:54
    at ExecutionContext._evaluateInternal (c:\Users\Yaas\Desktop\Generate-HoustonLibrary-Codes-master\node_modules\puppeteer\lib\ExecutionContext.js:122:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async ExecutionContext.evaluate (c:\Users\Yaas\Desktop\Generate-HoustonLibrary-Codes-master\node_modules\puppeteer\lib\ExecutionContext.js:48:12)
    at async c:\Users\Yaas\Desktop\Generate-HoustonLibrary-Codes-master\app.js:41:19
  -- ASYNC --
    at ExecutionContext.<anonymous> (c:\Users\Yaas\Desktop\Generate-HoustonLibrary-Codes-master\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.evaluate (c:\Users\Yaas\Desktop\Generate-HoustonLibrary-Codes-master\node_modules\puppeteer\lib\DOMWorld.js:112:20)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
  -- ASYNC --
    at Frame.<anonymous> (c:\Users\Yaas\Desktop\Generate-HoustonLibrary-Codes-master\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.evaluate (c:\Users\Yaas\Desktop\Generate-HoustonLibrary-Codes-master\node_modules\puppeteer\lib\Page.js:833:43)
    at Page.<anonymous> (c:\Users\Yaas\Desktop\Generate-HoustonLibrary-Codes-master\node_modules\puppeteer\lib\helper.js:112:23)
    at c:\Users\Yaas\Desktop\Generate-HoustonLibrary-Codes-master\app.js:41:30
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:2444) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2444) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by SharlSherif** [comment]
The Houston library changed its form. the script doesn't work anymore, we're looking for another library that could be used.

**Comment by maximousblk** [comment]
Any updates on this?
