### ISSUE TITLE
Error: listen EADDRINUSE: address already in use :::5000

### ISSUE THREAD

**Issue by mehdiben7** [SharlSherif/Generate-HoustonLibrary-Codes#8]
I apologize in advance, I don't know Node so I cannot give you information other than what the terminal yielded 

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::5000
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at Function.listen (/Users/mehdibenouhoud/Downloads/Generate-HoustonLibrary-Codes-master/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/mehdibenouhoud/Downloads/Generate-HoustonLibrary-Codes-master/app.js:79:5)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 5000
}

```

**Comment by mehdiben7** [comment]
No response
